//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkuSearch.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.CategoryTranslated = new HashSet<CategoryTranslated>();
            this.Product = new HashSet<Product>();
        }
    
        public int CategoryID { get; set; }
        public Nullable<int> CategoryParentRef { get; set; }
        public string CategoryName { get; set; }
    
        public virtual ICollection<CategoryTranslated> CategoryTranslated { get; set; }
        public virtual ICollection<Product> Product { get; set; }
    }
}
