//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkuSearch.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int CompanyID { get; set; }
        public string CompanyNameEn { get; set; }
        public string CompanyNameNative { get; set; }
        public string CompanyCountry { get; set; }
        public string CompanyCode { get; set; }
        public string CompanyLogo { get; set; }
        public string CompanyUrl { get; set; }
        public string CompanyAddress1 { get; set; }
        public string CompanyAddess2 { get; set; }
        public string CompanyTown { get; set; }
        public string CompanyCounty { get; set; }
        public string CompanyPostcode { get; set; }
        public string CompanyLocationCountry { get; set; }
        public Nullable<decimal> CompanyLatitude { get; set; }
        public Nullable<decimal> CompanyLongitude { get; set; }
    }
}
