//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkuSearch.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyTranslated
    {
        public int CompanyTranslatedID { get; set; }
        public int CompanyRef { get; set; }
        public string LanguageRef { get; set; }
        public string CompanyTranslatedName { get; set; }
    }
}
