//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkuSearch.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SkuSearchDBEntities : DbContext
    {
        public SkuSearchDBEntities()
            : base("name=SkuSearchDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AdditionalProperty> AdditionalProperty { get; set; }
        public DbSet<Category> Category { get; set; }
        public DbSet<CategoryTranslated> CategoryTranslated { get; set; }
        public DbSet<Company> Company { get; set; }
        public DbSet<Company_StockLocation> Company_StockLocation { get; set; }
        public DbSet<CompanyTranslated> CompanyTranslated { get; set; }
        public DbSet<Employee> Employee { get; set; }
        public DbSet<MultilanguageProperty> MultilanguageProperty { get; set; }
        public DbSet<Product> Product { get; set; }
        public DbSet<ProductStorage> ProductStorage { get; set; }
        public DbSet<StockLocation> StockLocation { get; set; }
        public DbSet<StockLocationTranslated> StockLocationTranslated { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Translation> Translation { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<WorkingHours> WorkingHours { get; set; }
        public DbSet<WorldLanguage> WorldLanguage { get; set; }
    }
}
