//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkuSearch.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public int CompanyRef { get; set; }
        public Nullable<int> CategoryRef { get; set; }
        public string ProductBarCode { get; set; }
        public string ProductAdditionalCode { get; set; }
        public string ProductImage { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
