//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkuSearch.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductStorage
    {
        public int ProductStorageID { get; set; }
        public int ProductRef { get; set; }
        public int StockLocationRef { get; set; }
        public string ProductStorageLocationStatus { get; set; }
        public Nullable<System.TimeSpan> ProductStorageDeliveryTime { get; set; }
        public Nullable<int> ProductStorageMaxShownQuantity { get; set; }
        public Nullable<int> ProductStorageMinShownQuantity { get; set; }
        public Nullable<int> ProductStorageQuantityLeft { get; set; }
    }
}
