//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkuSearch.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockLocationTranslated
    {
        public int StockLocationTraslatedID { get; set; }
        public int StockLocationRef { get; set; }
        public string WorldLanguageRef { get; set; }
        public string StockLocationTraslatedName { get; set; }
    
        public virtual WorldLanguage WorldLanguage { get; set; }
    }
}
