//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkuSearch.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockLocation
    {
        public int StockLocationID { get; set; }
        public string StockLocationName { get; set; }
        public int StockLocationOwnerType { get; set; }
        public string StockLocationDescription { get; set; }
        public Nullable<int> StockLocationWorkingHoursRef { get; set; }
        public string StockLocationPhone { get; set; }
        public string StockLocationEmail { get; set; }
        public string StockLocationUrl { get; set; }
        public string StockLocationAddress1 { get; set; }
        public string StockLocationAddess2 { get; set; }
        public string StockLocationTown { get; set; }
        public string StockLocationCounty { get; set; }
        public string StockLocationPostcode { get; set; }
        public string StockLocationCountry { get; set; }
        public decimal StockLocationLatitude { get; set; }
        public decimal StockLocationLongitude { get; set; }
    }
}
