//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkuSearch.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkingHours
    {
        public int StockLocationRef { get; set; }
        public Nullable<int> WorkingHoursDayOfWeek { get; set; }
        public Nullable<System.TimeSpan> WorkingHoursOpenTime { get; set; }
        public Nullable<System.TimeSpan> WorkingHoursCloseTime { get; set; }
        public Nullable<System.TimeSpan> WorkingHoursLunchTimeBegin { get; set; }
        public Nullable<System.TimeSpan> WorkingHoursLunchTimeEnd { get; set; }
    }
}
