//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkuSearch.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorldLanguage
    {
        public WorldLanguage()
        {
            this.MultilanguageProperty = new HashSet<MultilanguageProperty>();
            this.StockLocationTranslated = new HashSet<StockLocationTranslated>();
            this.Translation = new HashSet<Translation>();
        }
    
        public string WorldLanguageID { get; set; }
        public string WorldLanguageName { get; set; }
    
        public virtual ICollection<MultilanguageProperty> MultilanguageProperty { get; set; }
        public virtual ICollection<StockLocationTranslated> StockLocationTranslated { get; set; }
        public virtual ICollection<Translation> Translation { get; set; }
    }
}
